[workspace]
members = ["conditionals",
    "control-flow-conditionals", "for-loop", "loop-control", "loops", "shadowing",
    "variables/mutable",
    "variables/variables", "while-loops/user-input", "while-loops/while-loops",
]
